<a href="https://colab.research.google.com/github/Sujata456/-linearregression.ipynb/blob/main/linearregression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hi")

hi


In [ ]:
pip install numpy

In [ ]:
pip install panda

  Preparing metadata (setup.py) ... done
  Created wheel for panda: filename=panda-0.3.1-py3-none-any.whl size=7239 sha256=c587c981d733de2a981b229e5e98920f668948ea10d804ba23868fbada098839
  Stored in directory: /root/.cache/pip/wheels/df/5c/39/36f8dae25a1e88d6ec4411dec4a143781e64fdff6897758eec
Successfully built panda


In [ ]:
a=[12,14,16,18,20]
a

[12, 14, 16, 18, 20]

In [ ]:
b=[1200,1400,1600,1800,2000]
b

[1200, 1400, 1600, 1800, 2000]

In [ ]:
type(a)

list

In [ ]:
import pandas as pd  # helps to clean data i.e converting into

In [ ]:
x=pd.Series(a)
x

0    12
1    14
2    16
3    18
4    20
dtype: int64

In [ ]:

pip install scikit-learn# predfined libray for undearstanding data relation


ERROR: Invalid requirement: 'scikit-learn#': Expected end or semicolon (after name and no valid version specifier)
    scikit-learn#
                ^


In [ ]:
from sklearn import linear_model


In [ ]:
lr=linear_model.LinearRegression()

In [ ]:
x

0    12
1    14
2    16
3    18
4    20
dtype: int64

In [ ]:
y=pd.Series(b)
y

0    1200
1    1400
2    1600
3    1800
4    2000
dtype: int64

In [ ]:
lr.fit(x,y)

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [ ]:
import numpy as np

In [ ]:
x=np.array(x)   # converting list into array
x

array([12, 14, 16, 18, 20])

In [ ]:
y=np.array(y)
y

array([1200, 1400, 1600, 1800, 2000])

In [ ]:
lr.fit(x,y)


ValueError: Expected 2D array, got 1D array instead:
array=[12 14 16 18 20].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
x1=x.reshape(-1,1)  # converting 1d array into 2d array
x1

array([[12],
       [14],
       [16],
       [18],
       [20]])

In [ ]:
y1=y.reshape(-1,1)
y1

array([[1200],
       [1400],
       [1600],
       [1800],
       [2000]])

In [ ]:
lr.fit(x1,y1)

LinearRegression()

In [ ]:
lr.predict([[33]])

array([[3300.]])

In [ ]:
lr.coef_

array([[100.]])

In [ ]:
lr.intercept_

array([0.])

In [ ]:
p=lr.coef_*33+lr.intercept_
p

array([[3300.]])

In [ ]:
# task
# x1=1000,x2=2000,x3=3000


In [ ]:
X=[1000,2000,3000]
Y=[1200,1400,1600]

X1=pd.Series(X)
Y1=pd.Series(Y)

In [ ]:
X1=np.array(X1)
Y1=np.array(Y1)

In [ ]:
X1=X1.reshape(-1,1)
Y1=Y1.reshape(-1,1)

In [ ]:
lr.fit(X1,Y1)

LinearRegression()

In [ ]:
lr.predict([[7000]])

array([[2400.]])